### ISSUE TITLE
Question about gpu checkpoint/restore

### ISSUE THREAD

**Issue by freeliuzc** [RWTH-ACS/cricket#11]
Hi, CPU part has recorded `cuda_launch_kernel` and cricket can relaunch it in restore mode. Why do gpu code part need checkpoint/restore every sms/warps stats such as pc, callstack...
If we only checkpoint/restore global memory in GPU and relaunch kernel, is it theoretically work?

**Comment by n-eiling** [comment]
cricket can do checkpoint/restrore of the CPU part of the application as you described. Then we do not need to checkpoint/restore sms/warps, pc, etc. However, cricket can also checkpoint/restore the execution state of the GPU kernel (This is all the code in the gpu directory). This currently only works on the Pascal architecture.

**Comment by Magnus1cheng** [comment]
> cricket can do checkpoint/restrore of the CPU part of the application as you described. Then we do not need to checkpoint/restore sms/warps, pc, etc. However, cricket can also checkpoint/restore the execution state of the GPU kernel (This is all the code in the gpu directory). This currently only works on the Pascal architecture.

Hi, so based on my understanding. If I don't need c/r detailed gpu infos(like sms/ warps, pc, etc), I don't even need to use the cuda-gdb submodule at all?
And in the cpu directory, there's also functions to do checkpoint/restore, but how can I use these high-level checkpoint/restore? Do you have a demo codes or ideas? 
Because I'm using CUDA 12 on Ampere arch GPUs, so it's hard for me to make the cuda-gdb part compatiable in my environment. And actually I only want to use the top-level c/r logics. Thank you so much.

**Comment by n-eiling** [comment]
For most ML applications I know of, checkpointing the GPU Kernels using the cuda-gdb submodule does not make a lot of sense as the kernels are short running and it's not an issue to wait for their completion. I don't really have a good demo of how to use C/R yet. You can either call the RPC for checkpointing using e.g. rpcinfo. Alternatively, you can send the SIGUSR1 to the cricket server (https://github.com/RWTH-ACS/cricket/blob/b1d0b24cbf07e2002829d7b1da0396cd7647291f/cpu/cpu-server.c#L314). This will checkpoint the state of the CUDA APIs. For the client application you can use CRIU and checkpoint it as you would a container. To restore the CUDA API state, pass CRICKET_RESTORE=1 as environment to the cricket server (https://github.com/RWTH-ACS/cricket/blob/b1d0b24cbf07e2002829d7b1da0396cd7647291f/cpu/cpu-server.c#L206C17-L206C17)

**Comment by Magnus1cheng** [comment]
Thank you so much.  Another question is, https://github.com/RWTH-ACS/cricket/blob/b1d0b24cbf07e2002829d7b1da0396cd7647291f/cpu/cpu-server-runtime.c#L91C44-L91C44 here, why we need to initialize cuda runtime, instead of cuda driver. Cuda runtime is based on cuda driver, so I guess we should init cuda driver first, then cuda runtime.
And is it more reasonable to put `cudaSetDevice(0)` before resource manager initializations? Basiclly, cudaSetDevice would init cuda context for us, and then resource managers can have context to work with.

**Comment by n-eiling** [comment]
If I remember correctly, this is necessary to ensure that CUDA driver API and Runtime API are using the same context. cudaSetDevice will call cuInit to initialize the driver API and then they are using the same context.
This is probably only necessary if the resource managers do not call any CUDA runtime API. You are probably right, it would be better to put the initialization before the resource managers. It practice it shouldn't matter though - as long as the first CUDA API called is a runtime API function.

**Comment by Magnus1cheng** [comment]
Thank you for your clearification!
